# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  site-dir:  # id of input
    description: 'Folder containing sites with index.html'
    required: true
    default: ${{ github.workspace }}/_site
  report-dir:  # id of input
    description: 'Output folder containing accessibility report'
    required: true
    default: ${{ github.workspace }}/_report
outputs:
  time: # id of output
    description: 'time completed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -v
    - ${{ inputs.site-dir }}:/workspace/_site
    - -v
    - ${{ inputs.report-dir }}:/workspace/_report
