# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  site-dir-under-workspace:  # id of input
    description: 'Folder containing sites with index.html'
    required: true
    default: /
  report-dir-under-workspace:  # id of input
    description: 'Output folder containing accessibility report'
    required: true
    default: _report
outputs:
  time: # id of output
    description: 'time completed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
   - ${{ inputs.site-dir-under-workspace }}	
   - ${{ inputs.report-dir-under-workspace }}
